#!/usr/bin/env python

import csv
import os
import datetime

##############################################################################
def load_csv(filename):
    try:
        with open(filename, 'r') as csvfile:
            reader = csv.DictReader(csvfile)
            for row in reader:
                yield row

    except FileNotFoundError:
        print(f"Error: could not find file {filename}")

    except Exception as e:
        print(f"Error: {e}")

##############################################################################
def parse_row(data: dict,
              row: dict,
              fieldname: str,
              date_format: str,
              path: str):

    try:
        date = datetime.datetime.strptime(row[fieldname], date_format)

    except ValueError:
        return "Invalid date format"

    year = date.strftime("%Y")
    week_num = date.strftime("%U")
    week_dir = os.path.join(path, year, f"Week{week_num}")

#    try:
#        os.makedirs(week_dir, exist_ok=True)
#
#    except OSError as e:
#        print(f"Error: {e}")

    file_path = os.path.join(week_dir, f"{year}-Week{week_num}.csv")

    data.setdefault(file_path, []).append(row)

    return file_path

##############################################################################
def read_csv(filename: str, fieldname: str, date_format: str, path: str):
    data = {}

    for row in load_csv(filename):
        parse_row(data, row, fieldname, date_format, path)

    print("tbd")

##############################################################################
# Transaction_Number,Date,Description,Memo,Amount_Debit,Amount_Credit,Balance,Check_Number,Fees
# 2987467,04/30/2010,"Transaction COMMENT","Avg Checking Bal for Apr $169.52",0.00,,,,

filename = '8361157_50-2010-04.csv'
fieldname = 'Date'
date_format = '%m/%d/%Y'
path = "first_pass"

read_csv(filename, fieldname, date_format, path)
